import type { Metadata } from 'next'
import { LegalShell } from '@/components/landing/legal-shell'

export const metadata: Metadata = {
  title: 'Privacy',
  description: 'How StackPulse handles your data.',
}

export default function PrivacyPage() {
  return (
    <LegalShell title="privacy" slug="legal/privacy" updatedAt="May 2026">
      <p>
        StackPulse is a non-profit, open-source service that helps developers track GitHub release
        notes for the libraries they use. We try to collect as little as possible. This page
        explains what we collect, why, and what your rights are.
      </p>

      <h2>What we collect</h2>
      <ul>
        <li>
          <strong>GitHub profile basics</strong> when you sign in: your numeric GitHub user ID,
          email address, display name, and avatar URL. Authentication is handled by{' '}
          <a href="https://better-auth.com" target="_blank" rel="noopener noreferrer">
            Better Auth
          </a>
          .
        </li>
        <li>
          <strong>Your stack selection:</strong> the list of technologies and GitHub repository URLs
          you choose to follow.
        </li>
        <li>
          <strong>Digest signup email</strong> if you subscribe from a public page without signing
          in. We store the email address, signup source, and optional stack slug you subscribed
          from.
        </li>
        <li>
          <strong>Session cookies</strong> needed to keep you signed in.
        </li>
        <li>
          <strong>Server logs</strong> generated by our hosting provider (Vercel) — IP address, user
          agent, request path, response status. These are retained on Vercel&apos;s schedule.
        </li>
      </ul>

      <h2>What we don&apos;t collect</h2>
      <ul>
        <li>No third-party trackers or advertising pixels.</li>
        <li>No behavioural analytics that profile individuals.</li>
        <li>
          No access to your private GitHub repos. The OAuth scope is your public profile only.
        </li>
      </ul>

      <h2>How we use it</h2>
      <ul>
        <li>To show you a personalised feed of releases.</li>
        <li>To send your selected repos through GitHub&apos;s public release API every 4 hours.</li>
        <li>To summarise release notes using OpenRouter (model details are public).</li>
        <li>To respond to support requests you send us.</li>
        <li>To send opt-in release and upgrade digests if you subscribe on a public page.</li>
      </ul>

      <h2>Where it lives</h2>
      <p>
        Account data and release summaries are stored in Postgres on Neon (
        <a href="https://neon.tech" target="_blank" rel="noopener noreferrer">
          neon.tech
        </a>
        ), inside the EU/US region you signed up from. The app is hosted on Vercel. We do not sell
        or share your data with third parties.
      </p>

      <h2>Your rights</h2>
      <ul>
        <li>
          <strong>Access:</strong> sign in and you can see your full stack and feed.
        </li>
        <li>
          <strong>Deletion:</strong> sign in, open the user menu, click &quot;delete account&quot;.
          This wipes your account, stack, and read history immediately and cannot be undone.
        </li>
        <li>
          <strong>Questions:</strong> open an issue at{' '}
          <a
            href="https://github.com/daniel-ctn/stack-pulse"
            target="_blank"
            rel="noopener noreferrer"
          >
            github.com/daniel-ctn/stack-pulse
          </a>
          .
        </li>
      </ul>

      <h2>Changes</h2>
      <p>
        If this policy ever changes meaningfully, we&apos;ll update the date at the top and post a
        note in the repo&apos;s release notes — since you&apos;ll already be watching for those.
      </p>
    </LegalShell>
  )
}
